image: ibs:latest

test:
  script:
    - cd /builds/qa-maintenance/qam-oscplugin
    - zypper install --no-confirm m2crypto python-pycurl python-urlgrabber python-pytest python-mock python-prettytable
    - py.test tests
  tags:
    - qam
  only:
    - /^master.*$/
