include:
  - project: qa-maintenance/qamops
    file: /gitlab/templates.yml

variables:
  OSC_PACKAGE: osc-plugin-qam

#test:
#  stage: test
#  script:
#    - python3 -m pytest -v

publish_devel:
  extends: .obs:autoupdate
  variables:
    OSC_PROJECT: QA:Maintenance:Test
  rules:
    - if: $CI_PROJECT_NAMESPACE == "qa-maintenance" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish:
  extends: .obs:autoupdate
  variables:
    OSC_PROJECT: QA:Maintenance
  rules:
    - if: $CI_PROJECT_NAMESPACE == "qa-maintenance" && $CI_COMMIT_TAG
